apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: delivery-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5004
        env:
        - name: PORT
          value: "5004"
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-maps-secret
              key: api-key
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:5001"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:5006"